<?php

namespace AppBundle\Repository;

/**
 * YazilarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YazilarRepository extends \Doctrine\ORM\EntityRepository
{
}
