<?php

namespace AppBundle\Repository;

/**
 * YaziKategoriRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class YaziKategoriRepository extends \Doctrine\ORM\EntityRepository
{
}
